apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml

namespace: goapp

images:
- name: goapp
  newName: vitorsavicki/argo-cd-example
  newTag: 204accb508cb8977eebb23c1baa649efe0a2e5a2
